heat_template_version: 2014-10-16
parameters:
  str_length:
    type: number
    default: 64
resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: {get_param: str_length}
outputs:
  result:
    value: {get_attr: [random, value]}
