heat_template_version: 2014-10-16
parameters:
  file:
    type: string
    default: {get_file: test_script.sh}
resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 64
outputs:
  result:
    value: {get_attr: [random, value]}
